Improve progress message using new progress payload
datatrue-analytics/datatrue-api-client pull request #11
Opened 2020-08-11 09:02 UTC by oddui

Show number of crawled pages for coverage steps.

Dependency

https://github.com/Lens10/TagTrue/pull/1365

Example output
```
$ datatrue_client run 1 -a Sw16xGjfgJE2jkNXkGmaOg -t suite --timeout 600 --scheme http --host localhost:3030
datatrue_client: job=d63e2c37a5a83a05d9f16252cf03b3fa created for test="Welcome to DataTrue - here are some tests to get you started!"
datatrue_client: test_run_id=208 result=queued
datatrue_client: test_run_id=208 result=queued
datatrue_client: test_run_id=208 result=working
datatrue_client: test_run_id=208 result=working
datatrue_client: test_run_id=208 step=1 (0/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (0/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (0/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (1/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (1/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (1/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (2/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (2/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (3/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (3/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (3/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (4/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=1 (5/5 pages) total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=2 total_steps=7 result=working
datatrue_client: test_run_id=208 step=3 total_steps=7 result=working
datatrue_client: test_run_id=208 step=3 total_steps=7 result=working
datatrue_client: test_run_id=208 step=4 total_steps=7 result=working
datatrue_client: test_run_id=208 step=4 total_steps=7 result=working
datatrue_client: test_run_id=208 step=4 total_steps=7 result=working
datatrue_client: test_run_id=208 step=5 total_steps=7 result=working
datatrue_client: test_run_id=208 step=5 total_steps=7 result=working
datatrue_client: test_run_id=208 step=6 total_steps=7 result=working
datatrue_client: test_run_id=208 step=6 total_steps=7 result=working
datatrue_client: test_run_id=208 step=7 total_steps=7 result=working
datatrue_client: test_run_id=208 step=7 total_steps=7 result=working
datatrue_client: test_run_id=208 result=working
datatrue_client: test_run_id=208 result=working
datatrue_client: test_run_id=208 result=working
datatrue_client: test_run_id=208 result=failed
```

2020-08-12 07:10 UTC, gkampjes requested changes

2020-08-12 07:10 UTC, gkampjes commented on lib/datatrue_client/test_run.rb
> +        i = steps.index { |step| step['running'] }
```suggestion
        current_step_index = steps.index { |step| step['running'] }
```

2020-08-13 07:07 UTC, gkampjes approved these changes

2020-10-27 00:46 UTC, oddui commented
See readme and the [publishing guide](https://guides.rubygems.org/publishing/) to release a new version.

2020-10-27 00:55 UTC, merged